#!/usr/bin/env bash

set -e

source $SNAP/actions/common/utils.sh

# Variables
VERSION="master"
SCOPE="cluster"

KUBECTL="$SNAP/microk8s-kubectl.wrapper"
"$SNAP/microk8s-enable.wrapper" dns

# Waiting for the apiserver to start
sleep 5
${SNAP}/microk8s-status.wrapper --wait-ready --timeout 30 >/dev/null

# Check for arguments
while [[ $# -gt 0 ]]; do
  case $1 in
    --scope)
      read -ra SCOPE <<< "$2"
      shift
      shift
      ;;
    -*|--*)
      echo "Unknown option $1"
      exit 1
      ;;
  esac
done

echo "Enabling Litmuschaos..."

if [ "${SCOPE}" == "cluster" ]
then
  $KUBECTL apply -f ./litmus/cluster-k8s-manifest.yml
else
then
  $KUBECTL create ns litmus
  #Install CRDs, if SELF_AGENT env is set to TRUE
  $KUBECTL apply -f ./litmus/litmus-portal-crds.yml
  #Install ChaosCenter
  $KUBECTL apply -f ./litmus/namespace-k8s-manifest.yml -n litmus
fi

echo """
  _     _ _                            _                     
 | |   (_) |_ _ __ ___  _   _ ___  ___| |__   __ _  ___  ___ 
 | |   | | __| '_ ` _ \| | | / __|/ __| '_ \ / _` |/ _ \/ __|
 | |___| | |_| | | | | | |_| \__ \ (__| | | | (_| | (_) \__ \
 |_____|_|\__|_| |_| |_|\__,_|___/\___|_| |_|\__,_|\___/|___/

 Litmus is enabled. Happy hacking.
 
"""